"""Apply missing sheet_name to DatasetUpload

Revision ID: 00e392282678
Revises: ce32060e3771
Create Date: 2026-03-31 14:04:46.072465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e392282678'
down_revision: Union[str, Sequence[str], None] = 'ce32060e3771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_uploads', sa.Column('sheet_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_uploads', 'sheet_name')
    # ### end Alembic commands ###
