"""init

Revision ID: 63ed7e15ecf7
Revises: 
Create Date: 2026-03-30 18:27:50.840238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ed7e15ecf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('canonical_equipment',
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('canonical_label', sa.String(), nullable=True),
    sa.Column('normalized_label', sa.String(), nullable=True),
    sa.Column('alias_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_index(op.f('ix_canonical_equipment_canonical_id'), 'canonical_equipment', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_canonical_equipment_canonical_label'), 'canonical_equipment', ['canonical_label'], unique=False)
    op.create_index(op.f('ix_canonical_equipment_normalized_label'), 'canonical_equipment', ['normalized_label'], unique=False)
    op.create_table('dataset_uploads',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('dataset_schema', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_dataset_uploads_dataset_id'), 'dataset_uploads', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_uploads_name'), 'dataset_uploads', ['name'], unique=False)
    op.create_table('rule_sets',
    sa.Column('rule_set_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=True),
    sa.Column('ast_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('rule_set_id')
    )
    op.create_index(op.f('ix_rule_sets_rule_set_id'), 'rule_sets', ['rule_set_id'], unique=False)
    op.create_table('classification_runs',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('rule_set_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.rule_set_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_classification_runs_run_id'), 'classification_runs', ['run_id'], unique=False)
    op.create_table('column_mappings',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id_col', sa.String(), nullable=False),
    sa.Column('category_col', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_uploads.dataset_id'], ),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.create_index(op.f('ix_column_mappings_mapping_id'), 'column_mappings', ['mapping_id'], unique=False)
    op.create_table('match_records',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('source_row_index', sa.Integer(), nullable=True),
    sa.Column('source_equipment_id', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_equipment.canonical_id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_uploads.dataset_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_match_records_match_id'), 'match_records', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_records_match_id'), table_name='match_records')
    op.drop_table('match_records')
    op.drop_index(op.f('ix_column_mappings_mapping_id'), table_name='column_mappings')
    op.drop_table('column_mappings')
    op.drop_index(op.f('ix_classification_runs_run_id'), table_name='classification_runs')
    op.drop_table('classification_runs')
    op.drop_index(op.f('ix_rule_sets_rule_set_id'), table_name='rule_sets')
    op.drop_table('rule_sets')
    op.drop_index(op.f('ix_dataset_uploads_name'), table_name='dataset_uploads')
    op.drop_index(op.f('ix_dataset_uploads_dataset_id'), table_name='dataset_uploads')
    op.drop_table('dataset_uploads')
    op.drop_index(op.f('ix_canonical_equipment_normalized_label'), table_name='canonical_equipment')
    op.drop_index(op.f('ix_canonical_equipment_canonical_label'), table_name='canonical_equipment')
    op.drop_index(op.f('ix_canonical_equipment_canonical_id'), table_name='canonical_equipment')
    op.drop_table('canonical_equipment')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
