"""restore category_col

Revision ID: 66a60b082d34
Revises: ca9cd75e6acb
Create Date: 2026-03-31 10:57:32.852201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a60b082d34'
down_revision: Union[str, Sequence[str], None] = 'ca9cd75e6acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_mappings', sa.Column('category_col', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_mappings', 'category_col')
    # ### end Alembic commands ###
