"""add default and empty outputs

Revision ID: ca9cd75e6acb
Revises: d4f59a11cb0c
Create Date: 2026-03-31 10:53:57.190676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9cd75e6acb'
down_revision: Union[str, Sequence[str], None] = 'd4f59a11cb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_mappings', sa.Column('default_output', sa.String(), nullable=True))
    op.add_column('column_mappings', sa.Column('empty_output', sa.String(), nullable=True))
    op.drop_column('column_mappings', 'category_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_mappings', sa.Column('category_col', sa.VARCHAR(), nullable=True))
    op.drop_column('column_mappings', 'empty_output')
    op.drop_column('column_mappings', 'default_output')
    # ### end Alembic commands ###
