"""add mapping rules

Revision ID: cbdd21ea5d7b
Revises: 63ed7e15ecf7
Create Date: 2026-03-31 10:27:06.135160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdd21ea5d7b'
down_revision: Union[str, Sequence[str], None] = '63ed7e15ecf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_mappings', sa.Column('mapping_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_mappings', 'mapping_rules')
    # ### end Alembic commands ###
