"""add derived column settings

Revision ID: d4f59a11cb0c
Revises: cbdd21ea5d7b
Create Date: 2026-03-31 10:37:18.730935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f59a11cb0c'
down_revision: Union[str, Sequence[str], None] = 'cbdd21ea5d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_mappings', sa.Column('derived_column_name', sa.String(), nullable=True))
    op.add_column('column_mappings', sa.Column('data_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_mappings', 'data_type')
    op.drop_column('column_mappings', 'derived_column_name')
    # ### end Alembic commands ###
